[platformio]
default_envs = esp32c3supermini
src_dir = firmware/src
include_dir = firmware/include
test_dir = firmware/test

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
	bblanchon/ArduinoJson @ ^7.0.4

[env:esp32c3supermini]
extends = env
board = esp32-c3-devkitm-1
build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D DUX_PROFILE_NAME=\"esp32c3supermini\"
	-D DUX_LED_PIN=8
	-D DUX_LED_COUNT=60

[env:esp32dev]
extends = env
board = esp32dev
build_flags =
	-D DUX_PROFILE_NAME=\"esp32dev\"
	-D DUX_LED_PIN=5
	-D DUX_LED_COUNT=60

[env:esp32s3]
extends = env
board = esp32-s3-devkitc-1
build_flags =
	-D DUX_PROFILE_NAME=\"esp32s3\"
	-D DUX_LED_PIN=48
	-D DUX_LED_COUNT=60

[env:upload_esp32c3supermini]
extends = env:esp32c3supermini
upload_port = COM6
monitor_port = COM6

[env:upload_esp32dev]
extends = env:esp32dev
upload_port = COM8
monitor_port = COM8

[env:upload_esp32s3]
extends = env:esp32s3
upload_port = COM9
monitor_port = COM9
